# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GPUImageTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  pod 'GPUImage'

  # Pods for GPUImageTest

  target 'GPUImageTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPUImageTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
